name: WebAssembly

on: [push,pull_request]

jobs:
  build-wasm:
    name: "Build WebAssembly"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Build typescript buildings
      working-directory: ./wasm/typescript
      run: |
        npm install -g pnpm
        pnpm install
        pnpm build

    - name: Test typescript buildings
      working-directory: ./wasm/typescript
      run: |
        pnpm test

    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install hatch
      run: |
        python -m pip install hatch

    - name: Test WASI package
      working-directory: ./wasm/python/itkwasm-mesh-to-poly-data-wasi
      run: |
        hatch run test
